server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:chat
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  secret-key: secret
  expired-at-minutes: 5
  allowed-endpoints: [ /swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, /h2, /h2/**, /the-chat/v1/users ]
